document.write("<header class='major'>");
document.write("<h2>Get in touch</h2>");
document.write("</header>");
document.write("<p>If you have any questions, please feel free to reach out to us!</p>");
document.write("<ul class='contact'>");
document.write("<li class='icon solid fa-envelope'>Graduate Student Representative: Taylor Hutchison, <a href='mailto:aibhleog@tamu.edu'>aibhleog@tamu.edu</a></li>");
document.write("<li class='icon solid fa-envelope'>Postdocs &amp; Researchers contact: Terese Hansen, <a href='mailto:thidemannhansen@gmail.com'>thidemannhansen@gmail.com</a></li>");
document.write("<li class='icon solid fa-envelope'>Faculty contact &amp; Astronomy graduate program faculty advisor: Lucas Macri, <a href='mailto:lmacri@tamu.edu'>lmacri@tamu.edu</a></li>");
document.write("<li class='icon solid fa-phone'> TAMU Physics &amp; Astronomy Dept. #: (979) 845-7717</li>");
document.write("<li class='icon solid fa-home'>Dept of Physics &amp; Astronomy </br> 4242 TAMU </br> College Station, TX </br> 77843-4242</li>");
document.write("</ul>");
